### ISSUE TITLE
Please add Linux Support

### ISSUE THREAD

**Issue by sebi82** [ephtracy/ephtracy.github.io#172] opened 2020-08-21 21:13 UTC

**Comment by winkdong** [comment] 2020-10-06 12:55
AppImage can be great for all distros, or Flatpak.
I find it is much more comfortable to use than [Goxel](https://github.com/guillaumechereau/goxel) for me.
Thank you for this amazing application!

**Comment by v4dkou** [comment] 2020-11-09 09:26
For anyone else looking for a Linux version, I should mention that Wine works surprisingly well for MagicaVoxel

**Comment by dromer** [comment] 2020-11-22 11:23
Would also prefer a native version, even though with wine (`wine-4.0 (Debian 4.0-2)` here) it indeed works much better than expected :)

**Comment by gitowiec** [comment] 2020-12-26 21:54
@ephtracy is there any plans releasing this tool for Linux platform? What would you need to compile MagicalVoxel for Linux?

**Comment by culmat** [comment] 2020-12-27 10:59
this seems to be a duplicate of #162

**Comment by Shadowblitz16** [comment] 2022-01-11 21:43
please compile this for linux.

**Closed as completed** 2022-02-12 18:50 UTC

**Comment by dromer** [comment] 2022-02-12 21:23
Hmm, is that a no?

**Comment by twinflac** [comment] 2024-04-14 16:13
> Hmm, is that a no?

if guys not do this, maybe anyone else can will

**Comment by dromer** [comment] 2024-04-14 16:16
> if guys not do this, maybe anyone else can will

MagicaVoxel is not an opensource project.

**Comment by twinflac** [comment] 2024-04-14 16:19
> MagicaVoxel is not an opensource project.
this is not a limitation)

**Comment by dromer** [comment] 2024-04-14 17:10
> this is not a limitation)

Er .. how do you propose that anyone would port the software to a different OS (or architecture).. without having access to the source-code?

**Comment by twinflac** [comment] 2024-04-15 07:18
may be, i know guys that can do this
